version: '3'
services:
  php:
    build: ./php
    volumes:
      - ./symfony_project:/var/www/html
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - ./symfony_project:/var/www/html
  mysql:
    build: ./mysql
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8089:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: symfony
      PMA_PASSWORD: symfony
      PMA_ARBITRARY: 1

  node:
    build: ./node
    volumes:
      - ./symfony_project:/var/www/html